# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhoneSensorManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhoneSensorManager
  pod 'Charts'
  pod 'Euclid', '~> 0.1'
end
